### ISSUE TITLE
Blank google earth plugin screen - no map

### ISSUE THREAD

**Issue by marksev1** [nohal/gecomapi_pi#1]
Hi, 

as the title suggest I'm not getting the GE map. Just a blank window with the ui elements. I have the plugin enabled and also tried starting OpenCPN as admin, it didnt make any change.
Running latest stable Opencpn (ver 4) on Windows 7 64-bit. I can also tell you the version of GE that I have installed if you wish. 
How can I help debug my issue, thanks!

**Comment by nohal** [comment]
Yes, the GE version is the very bare minimum of the info needed. Note that the current GE versions do not offer the API this plugin relies on anymore (The last one that probably should work is 7.0, if I remember correctly)

**Comment by marksev1** [comment]
Seems to be 7.1.5.1557...so maybe I'm using a too new version. Question is though how to find the old one to download, and if it would be possible to run two versions installed :), one more bleeding edge the other older.

Another question, do you maybe know is there maybe some kml trick for injecting AIS data into a kml to  display in a separate GE window (in that case I wouldn't need to search for an older GE).? That it would refresh the data in the kml in real-time.

EDIT: downloaded the older official version 7.0.3.8542 and it works! :)

**Comment by nohal** [comment]
GE can be connected to an external source of data, which if I remember correctly can be a file or URL (The plugin uses it to plot the boat's position) Not very reliable to say the least. I'm not aware of any AIS->KML gateway (Which does not mean there isn't any)

**Comment by marksev1** [comment]
Cool, thanks so far! I'll close the issue since its resolved :)
