### ISSUE TITLE
GE Plugin 1.0: shows a white screen, no image

### ISSUE THREAD

**Issue by JohnEbert** [nohal/gecomapi_pi#2]
Opencpn 4.0.0, Windows 10 x64, Google Earth Pro, GE Plugin 1.0: shows a white screen, no image

I adjusted the Google Earth Pro views to not be active as advised in the setup for this plugin. The GE Plugin pops up into the opencpn screen and never populates any image other than a white screen.

**Comment by nohal** [comment]
Which version of GE? If 7.1+, you have to downgrade, Google has removed the API this plugin uses.

**Comment by JohnEbert** [comment]
Yes, I am using the most recent GE. I'll need to downgrade. Thank you! John

**Comment by JohnEbert** [comment]
I downgraded and still experience white screen view in the GE plugin.

Google Earth Pro

7.0.3.8542

Build Date

2/26/2013

Build Time

5:25:50 pm

**Comment by JohnEbert** [comment]
HI,
For no basis at all, the GE plugin began functioning in OpenCPN now. Happy
it works, mystified why it just sort of began working. Thought you would
like to know.
